api = "0.4"

[buildpack]
id = "jkutner/minecraft"
version = "0.2.2"
name = "Minecraft"
homepage = "https://github.com/jkutner/minecraft-buildpack"
description = "Create a Minecraft server for a Docker container"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.4.0"
    optional = true

  [[order.group]]
    id = "heroku/jvm"
    version = "0.1.0"

  [[order.group]]
    id = "jkutner/minecraft-server"
    version = "0.1.2"
