api = "0.3"

[buildpack]
id = "jkutner/minecraft"
version = "0.1.0"
name = "Minecraft"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.3.0"
    optional = true

  [[order.group]]
    id = "heroku/jvm"
    version = "0.1"

  [[order.group]]
    id = "jkutner/minecraft-server"
    version = "0.1.0"
