[stack]
id = "heroku-18"
build-image = "heroku/pack:18-build"
run-image = "heroku/pack:18"

[lifecycle]
version = "0.9.3"

[[buildpacks]]
  id = "jkutner/minecraft"
  uri = "docker://jkutner/minecraft:latest"

[[order]]
  [[order.group]]
    id = "jkutner/minecraft"