api = "0.4"

[buildpack]
id = "jkutner/minecraft-forge"
version = "0.1.0"
name = "Minecraft Forge"
homepage = "https://github.com/jkutner/minecraft-buildpack"
description = "Installs Minecraft Forge to a server"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "heroku-18"
