api = "0.2"

[buildpack]
id = "jkutner/minecraft-server"
version = "0.1.0"
name = "Minecraft"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "io.buildpacks.samples.stacks.bionic"
