name: Buildpackage
on:
    release:
        types:
            - published
jobs:
    create-package:
        name: Package, Publish, and Register
        runs-on:
            - ubuntu-latest
        steps:
            - id: checkout
              name: Checkout code
              uses: actions/checkout@v2
            - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
              name: Login to GitHub Package Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GHCR_TOKEN }}
            - id: package
              name: Package Buildpack
              uses: docker://docker.io/jkutner/gha-pack-package
              with:
                package: ghcr.io/${{ github.repository_owner }}/buildpacks/jkutner_minecraft
                publish: "true"
            # - id: register
            #   name: Register Buildpack
            #   uses: docker://ghcr.io/buildpacks/actions/registry:main
            #   with:
            #     token:   ${{ secrets.PUBLIC_REPO_TOKEN }}
            #     id:      jkutner/minecraft
            #     version: ${{ steps.version.outputs.version }}
            #     address: ghcr.io/jkutner/buildpacks/minecraft@${{ steps.package.outputs.digest }}
